# Generated by Django 5.1.2 on 2024-10-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default='', max_length=60),
        ),
    ]
