# Generated by Django 5.1.2 on 2024-10-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='foo',
            field=models.CharField(default='', max_length=60),
        ),
    ]
